### ISSUE TITLE
failed to start release 0.3

### ISSUE THREAD

**Issue by cfcodefans** [tech-bureau/catapult-service-bootstrap#21] opened 2019-03-21 03:35 UTC
generate-raw-addresses_1  | /bin-mount/generate-raw-addresses-if-needed: line 8:     6 Illegal instruction     (core dumped) /catapult/bin/catapult.tools.address --generate=${num_addresses} -n mijin-test > ${raw_addresses_path}

got error for the first time running "docker-compose up"
ran clean-all and reran "docker-compose up"
this error was reproduced.

is there anything needed to be configured?

thanks

**Comment by cfcodefans** [comment] 2019-03-21 03:39
actually the whole log for first run was

> store-addresses_1         | /ruby/lib/catapult/addresses.rb:59:in `break_into_sections': Not enough addresses (RuntimeError)
store-addresses_1         |     from /ruby/lib/catapult/addresses.rb:29:in `parse'
store-addresses_1         |     from /ruby/bin/store-addresses-if-needed.rb:20:in `<main>'
generate-raw-addresses_1  | /bin-mount/generate-raw-addresses-if-needed: line 8:     6 Illegal instruction     (core dumped) /catapult/bin/catapult.tools.address --generate=${num_addresses} -n mijin-test > ${raw_addresses_path}

**Comment by ccastromar** [comment] 2019-03-28 09:53
I got the same error using Ubuntu 16.04.
What is your OS?

**Comment by cfcodefans** [comment] 2019-03-28 10:03
centos 7

**Comment by ccastromar** [comment] 2019-03-28 10:10
Which version of ruby do you have? I have 2.3. 
I'll try to update to 2.5 -> It seems that the problem is that some executable: catapult.tools.address in docker image "catapult-tools" is throwing a core when executed.
My best guess is that someone overran an automatic array

**Comment by cfcodefans** [comment] 2019-03-28 13:14
hi, I tried to run
catapult/bin/catapult.tools.address --generate=50 -n mijin-test
and it failed too, I guess it is still a cpp issue

**Comment by gimre-xymcity** [comment] 2019-03-28 16:45
hi, `Illegal instruction (core dumped)` is most likely cause by old hardware...
@ccastromar what is the error that you're getting

**Comment by ccastromar** [comment] 2019-03-28 16:53
Hello @gimer I am running catapult inside a Ubuntu 16.04 box with Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
Docker errors:
store-addresses_1         | /ruby/lib/catapult/addresses.rb:59:in `break_into_sections': Not enough addresses (RuntimeError)
db_1                      | 2019-03-28T16:55:19.345+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7421M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
store-addresses_1         |     from /ruby/lib/catapult/addresses.rb:29:in `parse'
generate-raw-addresses_1  | /bin-mount/generate-raw-addresses-if-needed: line 8:     6 Illegal instruction     (core dumped) /catapult/bin/catapult.tools.address --generate=${num_addresses} -n mijin-test > ${raw_addresses_path}
db_1                      | 2019-03-28T16:55:20.416+0000 I STORAG

**Comment by ccastromar** [comment] 2019-03-28 18:16
Newer catapult versions like 0.3 don't work on older archs (like my Celeron one), it lacks some cpu instructions so that is the reason of the core dump.
@cfcodefans could you verify the arch of your CentOS 7?

**Comment by jontey** [comment] 2019-03-29 01:50
@cfcodefans  You can swap out the line 

```
FROM  techbureau/catapult-server:gcc-0.3.0.2
```

with
```
FROM  luxtagofficial/catapult-server:0.3.0.2
```

in `dockerfiles/catapult/Dockerfile` and `dockerfiles/nemgen/Dockerfile`. I've built those images to run on Celeron based CPUs.

**Comment by cfcodefans** [comment] 2019-03-29 06:40
yeah, thanks @jontey @gimer 
I switched to some new server, it could start now.
could there be any specs for cpu arch? or the makefile

**Comment by ccastromar** [comment] 2019-03-29 07:55
> @cfcodefans You can swap out the line
> 
> ```
> FROM  techbureau/catapult-server:gcc-0.3.0.2
> ```
> with
> 
> ```
> FROM  luxtagofficial/catapult-server:0.3.0.2
> ```
> in `dockerfiles/catapult/Dockerfile` and `dockerfiles/nemgen/Dockerfile`. I've built those images to run on Celeron based CPUs.

Started from scratch with these new Dockerfiles but still same error (core dumped).

**Comment by gimre-xymcity** [comment] 2019-03-29 09:28
@cfcodefans generally we require avx instruction set, so hardware above 2008 _should_ be fine

**Comment by iamNEMonic** [comment] 2019-04-10 05:57
Hello, I setup an Ubuntu 18.04 in my laptop with specs of Intel Core i5 2.5GHz with 8GB RAM. The error is same as the first one not enough addresses/Illegal instruction (core dumped). I followed all the instructions given on setting up docker and docker-compose, already tried FROM  luxtagofficial/catapult-server:0.3.0.2 also, but still no avail. Is there something required on the OS that I lack of? I tried setting up the same using DigitalOcean droplets with Ubuntu 18.04/8GB RAM, but the catapult ran smoothly, however when it comes to my laptop, I always encounter the same error of core dumped. Any recommendations?

**Comment by Alexhuszagh** [comment] 2019-05-30 02:48
I'm getting the same issue on a DigitalOcean image running Ubuntu 18.04.

**Comment by Alexhuszagh** [comment] 2019-05-30 02:53
```
cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
stepping        : 4
microcode       : 0x1
cpu MHz         : 2399.998
cache size      : 15360 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms
xsaveopt md_clear
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips        : 4799.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

Should support SSE2 and AVX extensions, so...

**Comment by kaiyzen** [comment] 2019-07-11 18:11
closing out, this should be logged over on catapult-server repo for any build/arch support issues

**Closed as completed by kaiyzen** 2019-07-11 18:11 UTC
